"""Add thumbnail_path to files properly

Revision ID: 1dbb25af1508
Revises: 8d6d2238618d
Create Date: 2025-06-21 21:45:59.857832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dbb25af1508'
down_revision: Union[str, Sequence[str], None] = '8d6d2238618d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('thumbnail_path', sa.String(), nullable=True))
    op.add_column('files', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'date_created')
    op.drop_column('files', 'thumbnail_path')
    # ### end Alembic commands ###
