"""Add description to tenants

Revision ID: 2785cbab2bc6
Revises: 73d3b46eacc7
Create Date: 2025-06-23 00:14:06.281078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2785cbab2bc6'
down_revision: Union[str, Sequence[str], None] = '73d3b46eacc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'description')
    # ### end Alembic commands ###
