"""Add public_id to File

Revision ID: 7a43af1373b3
Revises: 7861107a3d2a
Create Date: 2025-07-04 11:19:03.750215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a43af1373b3'
down_revision: Union[str, Sequence[str], None] = '7861107a3d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('files', sa.Column('public_id', sa.String(), nullable=True))
    op.alter_column(
        'files',
        'project_id',
        existing_type=sa.VARCHAR(),  # or sa.String()
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="project_id::uuid"
    )
    op.create_foreign_key(None, 'files', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.alter_column('files', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('files', 'public_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
